### ISSUE TITLE
No py36 package built

### ISSUE THREAD

**Issue by bwohlberg** [conda-forge/jonga-feedstock#1]
Issue: Python 3.7 is the only Python version for which a package is built (there is no Python 3.6 package available)

Can any conda-forge experts comment on why this might be? I can't see anything in the recipe that would be a candidate for being responsible for this restriction.

**Comment by bwohlberg** [comment]
@bgruening, could you please take a look at this?

**Comment by bgruening** [comment]
I think this will be fixed in a few hours.

**Comment by bwohlberg** [comment]
Thanks, the py36 versions were indeed built after your changes.

It's certainly not obvious that including the `python >=3.3` specification would lead to packages only being built for a single version of Python. Is this covered somewhere in the docs?

Also, with respect to the `skip: True  # [win or py2k]`, the only reason for the `win` exclusion is that one of the dependency packages is currently not supported on Windows. Is there a better way of including this restriction that would allow the use of `noarch: python` so that a version-independent package can be built?
